// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDItLTa4oUUZbe56gncNx60HyGl1k8Fk90',
    appId: '1:830200693487:web:869c9816b227a04ac3511a',
    messagingSenderId: '830200693487',
    projectId: 'ripen-go',
    authDomain: 'ripen-go.firebaseapp.com',
    databaseURL: 'https://ripen-go-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ripen-go.firebasestorage.app',
    measurementId: 'G-Y2JZXKZJC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahWpVGSWx8UOXr_DeEaG_4WQKwLfjvE4',
    appId: '1:830200693487:android:ef950c9e56d54e32c3511a',
    messagingSenderId: '830200693487',
    projectId: 'ripen-go',
    databaseURL: 'https://ripen-go-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ripen-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcD1ZoyhsQtpKJiSLwHLv587KBRdB4Wo',
    appId: '1:830200693487:ios:d96ba9a332d6a86bc3511a',
    messagingSenderId: '830200693487',
    projectId: 'ripen-go',
    databaseURL: 'https://ripen-go-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ripen-go.firebasestorage.app',
    iosBundleId: 'com.example.ripengo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDItLTa4oUUZbe56gncNx60HyGl1k8Fk90',
    appId: '1:830200693487:web:f0339c20d57522fac3511a',
    messagingSenderId: '830200693487',
    projectId: 'ripen-go',
    authDomain: 'ripen-go.firebaseapp.com',
    databaseURL: 'https://ripen-go-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ripen-go.firebasestorage.app',
    measurementId: 'G-B5JLNPRMXH',
  );
}
